version: "3.9"

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: agno_postgres
    restart: always
    environment:
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      POSTGRES_DB: ai
    ports:
      - "5532:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: agno_adminer
    restart: always
    ports:
      - "8080:8080"

